import type { SuggestionItem } from './types';

export const MOCK_SUGGESTIONS: SuggestionItem[] = [
  {
    id: 'mock-1',
    title: 'Tý và trò thả diều trên đê',
    idea: 'Tý, Bơ, Na cùng nhau làm diều giấy rồi ra bờ đê thả. Cơn gió lớn làm diều đứt dây, ba bạn chạy theo và tìm thấy diều mắc trên cây bàng.',
    topic: 'Trò chơi dân gian',
    setting: 'Bờ sông con đê',
    emotion: 'Vui vẻ háo hức',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-2',
    title: 'Bơ và hàng rào dâm bụt',
    idea: 'Bơ trốn tìm sau hàng rào dâm bụt trong trò chơi trốn tìm. Tý và Na tìm mãi không thấy, cuối cùng phát hiện Bơ đang ngủ gật trong bụi cây.',
    topic: 'Trò chơi dân gian',
    setting: 'Làng quê Việt Nam',
    emotion: 'Hài hước dở khóc dở cười',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-3',
    title: 'Cơn mưa rào mùa hạ',
    idea: 'Tý và Na đang chơi ngoài sân thì trời đổ mưa to. Hai bạn che ô chạy về nhà, dọc đường gặp Bơ đang ướt sũng vì quên mang ô.',
    topic: 'Mùa mưa rào',
    setting: 'Làng quê Việt Nam',
    emotion: 'Hồi hộp phấn khích',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-4',
    title: 'Mùa nước nổi về làng',
    idea: 'Mùa nước nổi lên, nước ngập đồng. Tý, Bơ, Na ngồi trên bè tre nhìn cá bơi qua vườn nhà. Các bạn cùng nhau thả thuyền giấy nhỏ.',
    topic: 'Mùa nước nổi',
    setting: 'Đồng lúa chín',
    emotion: 'Ngạc nhiên tò mò',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-5',
    title: 'Đêm trăng rằm hái sao',
    idea: 'Đêm trăng rằm, Tý và bạn bè ngồi trên sân gạch ngắm sao trời. Bơ kể chuyện ông trăng trên cung, còn Na hát bài ca dao mẹ hay hát.',
    topic: 'Đêm trăng rằm',
    setting: 'Làng quê Việt Nam',
    emotion: 'Hoài niệm nhẹ nhàng',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-6',
    title: 'Sáng sớm sương mai đi chợ',
    idea: 'Tý dậy sớm theo bà ra chợ quê. Sương mù giăng trắng con đường làng. Tý nhìn thấy đủ loại hoa quả tươi và nghe tiếng rao rộn ràng.',
    topic: 'Sương mai sớm',
    setting: 'Chợ quê sáng sớm',
    emotion: 'Ngạc nhiên tò mò',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-7',
    title: 'Bà và vườn cây sau nhà',
    idea: 'Na đến thăm bà, cùng bà chăm vườn cây sau nhà. Tý và Bơ phụ tưới cây, hái quả chín. Bà kể chuyện trồng cây từ thời trẻ.',
    topic: 'Gia đình & Làng quê',
    setting: 'Vườn cây nhà bà',
    emotion: 'Yêu thương ấm áp',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-8',
    title: 'Bữa cơm gia đình quê',
    idea: 'Cả nhà quây quần bên mâm cơm tối. Tý kể chuyện trường học, Bơ nghịch ngợm bị mẹ mắng nhẹ, Na phụ bà dọn bàn. Bữa cơm giản dị mà ấm áp.',
    topic: 'Gia đình & Làng quê',
    setting: 'Làng quê Việt Nam',
    emotion: 'Yêu thương ấm áp',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-9',
    title: 'Ngày đầu tiên đến trường',
    idea: 'Tý, Bơ, Na ngày đầu vào lớp 1. Tý hồi hộp cầm cặp mới, Bơ làm quen với bạn cùng bàn, Na khóc vì nhớ mẹ rồi lại cười khi được cô khen.',
    topic: 'Trường học & Bạn bè',
    setting: 'Trường tiểu học',
    emotion: 'Hồi hộp phấn khích',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-10',
    title: 'Trò chơi ô ăn quan giờ ra chơi',
    idea: 'Giờ ra chơi, Tý và Bơ chơi ô ăn quan trên sân trường. Na đứng xem rồi xin chơi thử, bất ngờ thắng Bơ khiến cả lớp bật cười.',
    topic: 'Trò chơi dân gian',
    setting: 'Trường tiểu học',
    emotion: 'Hài hước dở khóc dở cười',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-11',
    title: 'Thu hoạch lúa chín vàng',
    idea: 'Mùa gặt, Tý theo bố ra đồng lúa chín. Bơ và Na phụ bó lúa nhỏ. Ba bạn ngắm cánh cò bay qua đồng vàng óng ả dưới nắng chiều.',
    topic: 'Ký ức 4 mùa',
    setting: 'Đồng lúa chín',
    emotion: 'Hoài niệm nhẹ nhàng',
    script: '',
    createdAt: 0,
  },
  {
    id: 'mock-12',
    title: 'Đêm trung thu rước đèn',
    idea: 'Đêm trung thu, Tý cầm đèn ông sao, Bơ mang đèn cá chép, Na xách đèn kéo quân. Ba bạn rước đèn quanh làng, hát ca trung thu rộn ràng.',
    topic: 'Đêm trăng rằm',
    setting: 'Làng quê Việt Nam',
    emotion: 'Vui vẻ háo hức',
    script: '',
    createdAt: 0,
  },
];

export function getRandomMockSuggestions(count = 6): SuggestionItem[] {
  const shuffled = [...MOCK_SUGGESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((item, i) => ({
    ...item,
    id: `mock-${Date.now()}-${i}`,
    createdAt: Date.now(),
  }));
}
